name: Publish Go Package
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Force Go package publishing
        run: "${{github.workspace}}/publish-goproxy-pkg.sh -v ${{github.ref_name}}"