name: Publish Go Package
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Force Go package publishing
        run: make publish-pkg version="${{github.ref_name}}"